TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(PWD)/counter5.v
TOPLEVEL = counter5
COCOTB_TEST_MODULES = test_counter5

SIM = icarus   # or verilator, questa, vcs, etc.

include $(shell cocotb-config --makefiles)/Makefile.sim
