TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(PWD)/wallace_tree.v
TOPLEVEL = wallace_tree
MODULE = test_wallace_tree

SIM = icarus   # or verilator, questa, vcs, etc.

include $(shell cocotb-config --makefiles)/Makefile.sim
